import { ProjectsSectionType } from '@/lib/types/sections';
import { getId } from '@/lib/utils/helper';

export const projectsSection: ProjectsSectionType = {
  title: 'my projects',
  projects: [
    {
      id: getId(),
      name: 'RoadFusion',
      url: 'https://github.com/Abubakar-Imran/Road-Scene-Semantic-Segmentation-MLOps',
      repo: 'https://github.com/Abubakar-Imran/Road-Scene-Semantic-Segmentation-MLOps',
      img: '/projects/road-fusion1.png',
      year: 2025,
      tags: ['DL', 'CV', 'MLOps'],
    },
    {
      id: getId(),
      name: 'Facial Classification',
      url: 'https://github.com/Abubakar-Imran/Facial-Classification',
      repo: 'https://github.com/Abubakar-Imran/Facial-Classification',
      img: '/projects/facial-classification.png',
      year: 2025,
      tags: ['DL', 'ML'],
    },
    {
      id: getId(),
      name: 'LahoreEco',
      url: 'https://github.com/Abubakar-Imran/lahore-population-environment-analysis',
      repo: 'https://github.com/Abubakar-Imran/lahore-population-environment-analysis',
      img: '/projects/lahore-eco1.png',
      year: 2025,
      tags: ['ML', 'Remote Sensing', 'Data Analysis'],
    },
    {
      id: getId(),
      name: 'NIMUN',
      url: 'https://nimun.com.pk/',
      repo: 'https://github.com/TahaShah141/nimunWebsite',
      img: '/projects/nimun.png',
      year: 2025,
      tags: ['NextJs', 'TypeScript'],
    },
    {
      id: getId(),
      name: 'Faryaad',
      url: 'https://faryaad.netlify.app/',
      repo: 'https://github.com/Syed-MuhammadTaha/fund-raiser',
      img: '/projects/faryaad.png',
      year: 2024,
      tags: ['React', 'JavaScript'],
    },
    {
      id: getId(),
      name: 'Lyrics Vista',
      url: 'https://lyrics-vista.netlify.app/',
      repo: 'https://github.com/Abubakar-Imran/Lyrics-Vista',
      img: '/projects/lyrics-vista.png',
      year: 2023,
      tags: ['NLP', 'ML'],
    },
    {
      id: getId(),
      name: 'NexGen Homeware',
      url: 'https://nexgen-homeware.vercel.app/',
      repo: 'https://github.com/Abubakar-Imran/Ecommerce-Website',
      img: '/projects/nexgen-homeware.png',
      year: 2023,
      tags: ['React', 'JavaScript'],
    },
    {
      id: getId(),
      name: 'News App',
      url: 'https://github.com/Abubakar-Imran/News-App',
      repo: 'https://github.com/Abubakar-Imran/News-App',
      img: '/projects/news.png',
      year: 2023,
      tags: ['React', 'JavaScript'],
    },
    {
      id: getId(),
      name: 'Faryaad-e-Rahmat',
      url: 'https://faryaad-e-rahmat.vercel.app/',
      repo: 'https://github.com/Abubakar-Imran/Faryaad-e-Rahmat',
      img: '/projects/faryaad-e-rahmat.png',
      year: 2025,
      tags: ['HTML', 'CSS'],
    },
  ],
};
